const pathURI = {
  home: '/',
  onboarding: '/onboarding',
  signIn: '/signin',
  signUp: '/signup',
  forgotPwd: '/signup/forgot_pwd',
  welcome: '/signup/welcome',
  search: '/search',
  detail: '/detail',
  request: '/detail/request',
  favorite: '/favorite',
  mypage: '/mypage',
  createTrip: '/mypage/create_trip',
  modifyMyInfo: '/mypage/modify',
  promise: '/mypage/promise',
  block: '/mypage/block',
  noti: '/noti',
  chat: '/chat',
  chatRoom: '/chat/room',
  tutorial: '/tutorial',
  minitutorial: '/mini_tutorial',
};

const HeaderIncluded: string[] = [
  '/',
  '/search',
  '/detail',
  '/detail/request',
  '/favorite',
  '/mypage',
  '/mypage/block',
  '/mypage/create_trip',
  '/mypage/modify',
  '/mypage/promise',
  '/noti',
  '/chat',
  '/chat/room',
];

export { pathURI, HeaderIncluded };
